# Generated by Django 6.0.6 on 2026-06-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria di spesa',
                'verbose_name_plural': 'Categorie di spesa',
            },
        ),
        migrations.CreateModel(
            name='RichiestaRimborso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_spesa', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField()),
                ('riferimento_giustificativo', models.CharField(blank=True, default='', max_length=100)),
                ('stato', models.CharField(choices=[('IN_ATTESA', 'In attesa'), ('APPROVATA', 'Approvata'), ('RIFIUTATA', 'Rifiutata'), ('LIQUIDATA', 'Liquidata')], default='IN_ATTESA', max_length=20)),
                ('data_valutazione', models.DateTimeField(blank=True, null=True)),
                ('motivazione_rifiuto', models.TextField(blank=True, default='')),
                ('data_liquidazione', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='richieste', to='spese_aziendali.categoriaspesa')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to=settings.AUTH_USER_MODEL)),
                ('responsabile_valutazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valutazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta di rimborso',
                'verbose_name_plural': 'Richieste di rimborso',
                'ordering': ['-data_inserimento'],
            },
        ),
    ]
